/**
 * Crown Copyright (C) 2008 - 2011
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.actions;

import uk.nhs.cfh.dsp.srth.desktop.appservice.ApplicationService;
import uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.QueryResultsPanel;
import uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.model.table.ClinicalEntryTableModel;
import uk.nhs.cfh.dsp.srth.information.model.om.ehr.entry.ClinicalEntry;

import java.util.Collection;
import java.util.List;

// TODO: Auto-generated Javadoc
/**
 * A custom {@link org.jdesktop.application.Task} that publishes the intermediate results
 * generated by {@link uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.actions.PublishQueryResultsTask}
 *
 * <br>Version : @#VersionNumber#@
 * <br>Written by @author Jay Kola
 * <br>Created on 26-Mar-2010 at 10:32:55
 */
public class PopulateTableModelFromResultsTask extends PublishQueryResultsTask{

    /** The table model. */
    private ClinicalEntryTableModel tableModel;
    
    /** The query results panel. */
    private QueryResultsPanel queryResultsPanel;

    /**
     * Instantiates a new populate table model from results task.
     *
     * @param applicationService the application service
     * @param entries the entries
     * @param tableModel the table model
     * @param queryResultsPanel the query results panel
     */
    public PopulateTableModelFromResultsTask(ApplicationService applicationService, Collection<ClinicalEntry> entries,
                                             ClinicalEntryTableModel tableModel, QueryResultsPanel queryResultsPanel) {
        super(applicationService, entries);
        this.tableModel = tableModel;
        this.queryResultsPanel = queryResultsPanel;
        
		// clear existing model contents
		tableModel.clear();
    }

    /**
     * Process the intermediate results published by.
     *
     * @param list the list
     * {@link uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.actions.PublishQueryResultsTask} and add
     * them to the table model
     */
    @Override
    protected void process(List<List<Object>> list) {
        if (! isCancelled()) {
            // get table model and update
            tableModel.addAll(list);
        }
    }

    /* (non-Javadoc)
      * @see main.java.uk.nhs.cfh.dsp.srth.desktop.modules.queryresultspanel.actions.PublishQueryResultsFromResultSetTask#succeeded(java.lang.Void)
      */
    @Override
    protected void succeeded(Void arg0) {

        queryResultsPanel.renderColumns();
        setMessage("Successfully displayed all results");
    }
}
